//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLocation
    {
        public EventLocation()
        {
            this.Schedulers = new HashSet<Scheduler>();
        }
    
        public int EventLocationID { get; set; }
        public string EventLocationName { get; set; }
        public long SchoolID { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Scheduler> Schedulers { get; set; }
        public virtual School School { get; set; }
    }
}
