//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredUser
    {
        public long UserID { get; set; }
        public int UserRoleID { get; set; }
        public long SchoolID { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool IsLocked { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> NumAttempts { get; set; }
        public int LockedQuestionID { get; set; }
        public string LockedAnswer { get; set; }
    
        public virtual LockedQuestion LockedQuestion { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual School School { get; set; }
    }
}
