//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Scheduler
    {
        public long SchedulerID { get; set; }
        public Nullable<System.DateTime> EventStart { get; set; }
        public Nullable<System.DateTime> EventEnd { get; set; }
        public string EventDescription { get; set; }
        public string EventSubject { get; set; }
        public Nullable<int> EventLocationID { get; set; }
        public long SchoolID { get; set; }
    
        [JsonIgnore]
        public virtual EventLocation EventLocation { get; set; }
        [JsonIgnore]
        public virtual School School { get; set; }
    }
}
