//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {            
            this.EventLocations = new HashSet<EventLocation>();
            this.RegisteredUsers = new HashSet<RegisteredUser>();
            this.Schedulers = new HashSet<Scheduler>();
        }
    
        public long SchoolID { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public string Mascot { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string ButtonColor { get; set; }
        public string BannerColor { get; set; }
        public string LogoLocation { get; set; }
    
        [JsonIgnore]
        public virtual ICollection<EventLocation> EventLocations { get; set; }
        [JsonIgnore]
        public virtual ICollection<RegisteredUser> RegisteredUsers { get; set; }
        [JsonIgnore]
        public virtual ICollection<Scheduler> Schedulers { get; set; }
    }
}
