//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uzoneEntities : DbContext
    {
        public uzoneEntities()
            : base("name=uzoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EventLocation> EventLocations { get; set; }
        public DbSet<LockedQuestion> LockedQuestions { get; set; }
        public DbSet<RegisteredUser> RegisteredUsers { get; set; }
        public DbSet<Scheduler> Schedulers { get; set; }
        public DbSet<School> Schools { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
    }
}
